// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finance.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contains the transaction history of an account.
type AccountTransactions struct {
	Field                []*Field       `protobuf:"bytes,1,rep,name=field" json:"field,omitempty"`
	Transaction          []*Transaction `protobuf:"bytes,2,rep,name=transaction" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccountTransactions) Reset()         { *m = AccountTransactions{} }
func (m *AccountTransactions) String() string { return proto.CompactTextString(m) }
func (*AccountTransactions) ProtoMessage()    {}
func (*AccountTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04e2e1c1ba79a81, []int{0}
}

func (m *AccountTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTransactions.Unmarshal(m, b)
}
func (m *AccountTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTransactions.Marshal(b, m, deterministic)
}
func (m *AccountTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTransactions.Merge(m, src)
}
func (m *AccountTransactions) XXX_Size() int {
	return xxx_messageInfo_AccountTransactions.Size(m)
}
func (m *AccountTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTransactions proto.InternalMessageInfo

func (m *AccountTransactions) GetField() []*Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *AccountTransactions) GetTransaction() []*Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

// Name of the values in this column.
type Field struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04e2e1c1ba79a81, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// Values of a single transaction.
type Transaction struct {
	Value                []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04e2e1c1ba79a81, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountTransactions)(nil), "message.AccountTransactions")
	proto.RegisterType((*Field)(nil), "message.Field")
	proto.RegisterType((*Transaction)(nil), "message.Transaction")
}

func init() { proto.RegisterFile("finance.proto", fileDescriptor_c04e2e1c1ba79a81) }

var fileDescriptor_c04e2e1c1ba79a81 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0xcc, 0x4b,
	0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x55, 0x2a, 0xe6, 0x12, 0x76, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x09, 0x29, 0x4a,
	0xcc, 0x2b, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x2b, 0x16, 0x52, 0xe1, 0x62, 0x4d, 0xcb, 0x4c,
	0xcd, 0x49, 0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd3, 0x83, 0xaa, 0xd7, 0x73, 0x03,
	0x89, 0x06, 0x41, 0x24, 0x85, 0xcc, 0xb8, 0xb8, 0x4b, 0x10, 0xba, 0x24, 0x98, 0xc0, 0x6a, 0x45,
	0xe0, 0x6a, 0x91, 0x4c, 0x0c, 0x42, 0x56, 0xa8, 0x24, 0xcd, 0xc5, 0x0a, 0x36, 0x47, 0x48, 0x88,
	0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x52,
	0xe6, 0xe2, 0x46, 0xd2, 0x28, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0x76, 0x09,
	0x67, 0x10, 0x84, 0x03, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xd7, 0x60, 0xb7, 0xcf, 0x00, 0x00,
	0x00,
}
